image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

stages:
  - images
  - infra

.systemctl: &systemctl
  tags:
    - lxc
    - amd64
  stage: images
  script:
    - systemctl is-system-running -q

debian-9:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-9

debian-10:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

debian-11:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-11

ubuntu-18.04:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/ubuntu-18.04

ubuntu-20.04:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/ubuntu-20.04

ubuntu-21.04:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/ubuntu-21.04

centos-7:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/centos-7

centos-8:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/centos-8

fedora-33:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-33

fedora-34:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34

opensuse-15.2:image:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/opensuse-15.2

nesting: # test container nesting on runner
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34:podman
  tags:
    - lxc
    - amd64
  stage: infra
  needs: []
  script:
    - unset TMPDIR
    - podman run $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34:podman true
