image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

stages:
  - images
  - infra

.systemctl: &systemctl
  tags:
    - lxc
  stage: images
  script:
    - systemctl is-system-running -q

image:debian-10:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

image:fedora-34:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34

nesting: # test container nesting on runner
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34:podman
  tags:
    - lxc
  stage: infra
  needs: []
  script:
    - podman run $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34:podman true
