image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

stages:
  - systemctl

.systemctl: &systemctl
  tags:
    - lxc
  stage: systemctl
  script:
    - systemctl is-active dbus.service -q

systemctl:debian-10:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10
