image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

stages:
  - images
  - infra

.systemctl: &systemctl
  tags:
    - lxc
    - amd64
  stage: images
  script:
    - systemctl is-system-running -q

image:debian-10:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/debian-10

image:ubuntu-18.04:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/ubuntu-18.04

image:ubuntu-20.04:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/ubuntu-20.04

image:centos-7:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/centos-7

image:centos-8:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/centos-8

image:fedora-33:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-33

image:fedora-34:
  <<: *systemctl
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34

nesting: # test container nesting on runner
  image: $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34:podman
  tags:
    - lxc
    - amd64
  stage: infra
  needs: []
  script:
    - unset TMPDIR
    - podman run $CI_REGISTRY/labs/lxc-gitlab-runner/fedora-34:podman true
