---
# upstream repository is needed for skopeo (to run OCI containers)
# FUTURE: skopeo should be in distro repositories since Ubuntu 20.10
- name: add kubic:libcontainers:stable signing key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
    state: present

- name: add kubic_libcontainers:stable OBS repo
  apt_repository:
    repo: >
      deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /
    state: present
    update_cache: true

- name: install LXC dependencies
  apt:
    name:
      - lxc
      - skopeo
      - umoci
      - jq
    state: present

- name: clone custom runner scripts
  git:
    dest: '{{ lxc_git_dir }}'
    repo: https://gitlab.nic.cz/labs/lxc-gitlab-runner.git

- name: create config dir
  file:
    path: '/home/{{ lxc_user }}/.config/lxc'
    state: directory
    owner: '{{ lxc_user }}'
    group: '{{ lxc_user }}'
    mode: 0750

- name: deploy default lxc.conf
  template:
    src: lxc.conf
    dest: /home/{{ lxc_user }}/.config/lxc/default.conf

- name: add subuid/subgid for LXC user
  lineinfile:
    line: gitlab-runner:{{ lxc_id_start }}:65536
    path: '{{ item }}'
  loop:
    - /etc/subuid
    - /etc/subgid

- name: configure lxc-usernet
  template:
    src: lxc-usernet
    dest: '/etc/lxc/lxc-usernet'

- name: enable lingering for LXC user
  command: "loginctl enable-linger {{ lxc_user }}"

# TODO nesting
