---
- hosts: all
  become: true
  vars_prompt:
    - name: gitlab_runner_registration_token
      prompt: GitLab runner registration token (empty to skip)
      private: false
  pre_tasks:
    - name: update package cache
      apt:
        update_cache: yes
    - name: update all packages
      apt:
        name: "*"
        state: latest
  roles:
    - lxc
    - gitlab-runner
